name: Enviar mensagem Telegram

on:
  schedule:
    - cron: "0 */2 * * *"  # a cada 2 horas (UTC)
  workflow_dispatch:       # permite rodar manualmente
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script
        run: python bot_telegram.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
